### ISSUE TITLE
fates tutorial: checkout_externals svn authentication error for ccsm

### ISSUE THREAD

**Issue by glemieux** [glemieux/fates#5]
@rgknox and @ckoven, in section 0-5 of the tutorial I've hit an authentication error in trying to ```./manage_externals/checkout_externals``` in the ```~/FatesTutorial_Feb2019/ctsm>``` directory.  It's asking for authentication and my UCAR password doesn't seem to work.  Here's the output:

```
glemieux@cheyenne6:~/FatesTutorial_Feb2019/ctsm> ./manage_externals/checkout_externals 
Processing externals description file : Externals.cfg
Processing externals description file : Externals_CISM.cfg
Processing externals description file : Externals_CLM.cfg
Checking status of externals: cism, source_cism, clm, fates, ptclm, mosart, cime, rtm, 
Checking out externals: cism, clm, mosart, cime, rtm, 
Processing externals description file : Externals_CISM.cfg
Checking out externals: source_cism, Authentication realm: <https://svn-ccsm-models.cgd.ucar.edu:443> ccsm:models
Password for 'glemieux': ****************

Authentication realm: <https://svn-ccsm-models.cgd.ucar.edu:443> ccsm:models
Username: glemieux
Password for 'glemieux': ****************

Authentication realm: <https://svn-ccsm-models.cgd.ucar.edu:443> ccsm:models
Username: 
Password for '': 

ERROR: Failed with output:
    svn: E215004: Unable to connect to a repository at URL 'https://svn-ccsm-models.cgd.ucar.edu/cism/branch_tags/longer_var_list_tags/longer_var_list_n01_cism2_1_develop_n02'
    svn: E215004: No more credentials or we tried too many times.
    Authentication failed

ERROR: In directory
    /gpfs/u/home/glemieux/FatesTutorial_Feb2019/ctsm
Process did not run successfully; returned status 1:
    svn checkout --quiet https://svn-ccsm-models.cgd.ucar.edu/cism/branch_tags/longer_var_list_tags/longer_var_list_n01_cism2_1_develop_n02 /gpfs/u/home/glemieux/FatesTutorial_Feb2019/ctsm/components/cism/glimmer-cism
See above for output from failed command.
Please check the log file manage_externals.log for more details.
```
On a related note, am I correct in running the command from the ```~/FatesTutorial_Feb2019/ctsm>``` directory?  Re-reading the tutorial workflow from 0-4, it could suggest running the command from the ```~/FatesTutorial_Feb2019/TestCloneSpace/ctsm> ``` directory.  Interestingly, running the checkout from the ```ctsm``` root in the ```TestCloneSpace``` directory works fine.  Was the original intent of the tutorial to run from the ```TestCloneSpace``` directory and I misinterpreted it?

**Comment by rgknox** [comment]
Hi Greg,

That was the intent, this command should be executed on the fresh clone.  If the wiki was not clear on that, could you help correct it?
My guess is that the already existing clone is now out of date.

**Comment by glemieux** [comment]
Roger that; will do.  Was the intent to help the user get oriented to the mechanics of updating and syncing fates?  I ask as it looks like the tutorial specifies in section 1-1 that the scripts are to be run from ```~/FatesTutorial_Feb2019/ctsm/cime/scripts>``` and *not* from the fresh clone, correct?

**Comment by rgknox** [comment]
Yeah, creating the fresh clone and checking out fates is just optional practice.  
We did this for two reasons.  Some users may had already gone through 4 days of training on how to download or clone CTSM, so we wanted to give them a way of bypassing that.  Also, we didn't want the rest of the tutorial to rely on the user getting the fresh clone correctly checked out and synced.

**Comment by glemieux** [comment]
That makes sense; get the attendees to focus on what they're really there for which is using FATES.
