### ISSUE TITLE
Clarify tutorial setup steps wrt making fresh clones

### ISSUE THREAD

**Issue by glemieux** [glemieux/fates#6]
Hi Greg,

That was the intent, this command should be executed on the fresh clone.  If the wiki was not clear on that, could you help correct it?
My guess is that the already existing clone is now out of date.

_Originally posted by @rgknox in https://github.com/glemieux/fates/issues/5#issuecomment-475330852_

**Comment by glemieux** [comment]
Clarified the language.  If you get a chance to take a look @rgknox, let me know if you think I communicated the intent clearly/correctly.

**Comment by rgknox** [comment]
it looks great, thanks @glemieux !
