### ISSUE TITLE
JOB_QUEUE ctsm script setting

### ISSUE THREAD

**Issue by glemieux** [glemieux/fates#7]
@rgknox in the tutorial the 1x1 script has a setting ```JOB_QUEUE```.  How do I determine what to set here?  Here's the script context:
```
# Configuration for CTSM on cheyenne
CIME_MODEL=cesm
MACH=cheyenne
COMP=I2000Clm50FatesGs
PROJECT=P93300041
JOB_QUEUE=R4231271
```
Looking through the [Cheyenne user's guide on job submissions](https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/running-jobs/job-submission-queues), it seems to suggest that you denote the nominal name for the queue (e.g. "regular").  That said I also saw on [this page](https://www2.cisl.ucar.edu/resources/computational-systems/cheyenne/running-jobs/submitting-jobs-pbs#Batch-jobs) that using ```qcmd``` automatically starts the job on the "regular" queue:

> **Alternative - qcmd**: For running resource-intensive tasks such as CESM and WRF builds or other compiles with three or more threads, CISL provides qcmd. This script starts a non-interactive job on a single batch node in the Cheyenne "regular" queue with a default wall-clock time of 1 hour.

Given this, what is the significance of the ```JOB_QUEUE``` setting in the script?

**Comment by rgknox** [comment]
You can just leave that blank, and remove the argument from the case setup.  That job queue was something only relevant to the special PROJECT used for the tutorial.

**Comment by glemieux** [comment]
Thanks!
