### ISSUE TITLE
Do variables defined during type defintion within a module need to be specified as public?

### ISSUE THREAD

**Issue by glemieux** [glemieux/fates#8]
For example in `EDTypesMod.F90` the `ed_cohort_type` is defined.  Do the variables defined for this type also need to be specified as public/private?

Relevant to https://github.com/NGEET/fates/issues/502.

**Comment by rgknox** [comment]
I don't think so ...  The whole structure will be defined as public or private.  I think the key is that we declare the type as public.  Since we are using a hierarchy of nested linked lists, the actual targets are almost always local memory anyway:

fates%site%patch%cohort

**Comment by glemieux** [comment]
Thanks @rgknox.  I whipped up a little script to test this as well and played around with the where to define `public` and `private`.  Find the syntax for defining the public type was harder, but it made syntactic sense when I finally saw it :man_facepalming: 
```
module TestMod
    implicit none 
    private

    integer, public :: a = 1
    integer, public :: b = 2

    type, public :: testtype 
        real, private :: c = 5.0
        real :: d = 7.5
        real :: g = 2.5 
    end type testtype

end module TestMod

program maintest

    use TestMod
    implicit none

    type (testtype) :: mytype 
    integer :: e
    real :: z

    e = a + b
    print *, e
    
    z = mytype%d + mytype%g
    print *, z

end program maintest
```
